export const POSTS_COUNT = 25; // Количество постов (фотографий)
export const MIN_COMMENTS_COUNT = 1; // Минимальное число комментариев к фото
export const MAX_COMMENTS_COUNT = 30; // Максимальное число комментариев к фото
export const MIN_LIKES_COUNT = 1; // Минимальное число лайков к фото
export const MAX_LIKES_COUNT = 30; // Максимальное число лайков к фото
export const SHOWN_COMMENTS_COUNT = 5; // Количество комментариев отображаемых по умолчанию
export const AVATARS_COUNT = 6; // Количество аватарок
export const HASHTAG_PATTERN = /^#[a-zа-яё0-9]{1,19}$/i; // Шаблон для хэштега
export const DESCRIPTION_LENGTH = 140; // Максимальная длина комментария
export const MAX_HASHTAGS_COUNT = 5; // Максимальное количество хэштегов
export const MIN_HASHTAG_LENGTH = 2; // Минимальная длина хэштега
export const MAX_HASHTAG_LENGTH = 20; // Минимальная длина хэштега
export const HASHTAGS_SPLITTER = ' '; // Разделитель хэштегов
